default: &default
  adapter: mysql2
  database: totec
  username: totecer
  password: ZZ53HbhI
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000
development:
  <<: *default
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
production:
  <<: *default
  host: localhost
  pool: 5
  timeout: 5000

