common: &default_settings
  license_key: '6bac8718aefc4a7ddabb270d5ef6f250582db0e4'
  # agent_enabled: auto
  app_name: totec
  monitor_mode: true
  developer_mode: false
  log_level: info
  # Optionally set the path to the log file This is expanded from the
  # root directory (may be relative or absolute, e.g. 'log/' or
  # '/var/log/') The agent will attempt to create this directory if it
  # does not exist.
  # log_file_path: 'log'
  browser_monitoring:
      auto_instrument: true
  # If a proxy is used, the host setting is required.  Other settings
  # are optional. Default port is 8080.
  # proxy_host: hostname
  # proxy_port: 8080
  # proxy_user:
  # proxy_pass:
  audit_log:
    enabled: false
  capture_params: false
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    explain_enabled: true
    explain_threshold: 1
  error_collector:
    enabled: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"
  # capture_memcache_keys: true
development:
  <<: *default_settings
  # Turn on communication to New Relic service in development mode
  monitor_mode: true
  app_name: totec(Development)
  developer_mode: true
test:
  <<: *default_settings
  monitor_mode: false
production:
  <<: *default_settings
  monitor_mode: true
staging:
  <<: *default_settings
  monitor_mode: true
  app_name: totec(Staging)
