# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 632e16800291a7ecf3f2d4e1e12bd82a6cbb945e0f607ebcfbf1211214787082d5716c8d37e99fddd5f7b868f6e5595bfca7e2cc255fa39bb4c105a04087bd6b

test:
  secret_key_base: c947b829160dbd1f10136567775dab2704db29560f05745ff9b4caaccec72a681e4c9ca463a031617589eb8f488aa88e459e32eba2e60274befeff6df6dcf18c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
